routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
// Route::get('roles', function(){
// 	return \App\Role::with('user')->get();
// });

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {

	Route::get('perfil/{id}', 'UserController@perfil');
	Route::patch('cambiar-empresa', 'UserController@cambiarempresa');

	Route::resource('autobuses', 'AutobusController');

	Route::resource('empleados', 'EmpleadoController');
	Route::patch('eliminar-empleado/{id}', 'EmpleadoController@eliminar');
	Route::patch('agregar-empleado', 'EmpleadoController@agregar');
	Route::get('registrar-empleado', 'EmpleadoController@registrar');
	Route::post('registrar-empleado', 'EmpleadoController@guardado');
	Route::patch('cambiar-role', 'EmpleadoController@role');
	Route::patch('cambiar-foto', 'EmpleadoController@cambiarfoto');

	Route::resource('rutas', 'RutaController');
	Route::resource('empresas', 'EmpresaController');
	Route::resource('licencias', 'LicenciaController');
	Route::resource('navegacion', 'NavegacionController');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('usuarios', 'UserController');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

resources/views/buses/crear.blade.php
@extends('layouts.app', ['activePage' => 'typography', 'titlePage' => __('Typography')])

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Autobuses</h4>
        <p class="card-category"></p>
      </div>
      <div class="card-body">
        <div id="autobuses">
          <div class="card-title">
            <h2>Crear Bus</h2>
            <br>
            
            <form action="{{ url('autobuses') }}" method="post" enctype="multipart/form-data">
             @csrf
              <div class="form-group">
                <label for="placa">Placa</label>
                <input required type="text" class="form-control" id="placa" name="placa">
              </div>

              <br>

              <div class="form-group">
                <label for="capacidad">Capacidad de personas</label>
                <input required type="number" class="form-control" id="capacidad" name="capacidad">
              </div>

              <br>

              <div class="form-group">
                <label for="capacidad">Cilindraje</label>
                <input required type="text" class="form-control" id="capacidad" name="cilindraje">
              </div>

              <br>

              <div class="input-group mb-3">
                <label for="capacidad">foto</label>
                <br>
                  <input required type="file" class="form-control" placeholder="Foto" name="foto">
                  <div class="input-group-append">
                    <div class="input-group-text">
                      <span class="fas fa-user"></span>
                    </div>
                  </div>
              </div>

              <br>

               <div class="form-group">
                <label for="empresa">Licencia</label>
                <select required class="form-control" data-style="btn btn-link" id="empresa" name="licencia_id">
                  <option value="" selected disabled>Seleccione...</option>

                  @foreach ($rowsl as $row)
                  <option value="{{$row->id}}">{{$row->tipo}}</option>
                  @endforeach

                </select>
              </div>

              <br>


              <div class="form-group">
                <label for="operacion">Estado Operativo</label>
                 <select required class="form-control" data-style="btn btn-link" id="operacion" name="operacion_estado">
                  <option value="" selected disabled>Seleccione...</option>
                  <option value="Activo">Activo</option>
                  <option value="Inactivo">Inactivo</option>
                </select>
              </div>

              @if(Auth::user()->role_id==1)

               <div class="form-group">
                <label for="licencia">Estado de la licencia</label>
                 <select required class="form-control" data-style="btn btn-link" id="licencia" name="licencia_estado">
                  <option value="" selected disabled>Seleccione...</option>
                  <option value="Activa">Activa</option>
                  <option value="Inactiva">Inactiva</option>
                </select>
              </div>

              <br>

               <div class="form-group">
                <label for="empresa">Empresa</label>
                <select required class="form-control" data-style="btn btn-link" id="empresa" name="empresa_id">
                  <option value="" selected disabled>Seleccione...</option>

                  @foreach ($rows as $row)
                  <option value="{{$row->id}}">{{$row->nombre}}</option>
                  @endforeach

                </select>
              </div>
              @endif
              
              <br>

              <button type="submit" class="btn btn-success">Submit</button>
              <a href="{{url('autobuses')}}" class="btn btn-info float-right">Volver</a>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/buses/editar.blade.php
@extends('layouts.app', ['activePage' => 'typography', 'titlePage' => __('Typography')])

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Autobuses</h4>
        <p class="card-category"></p>
      </div>
      <div class="card-body">
        <div id="autobuses">
          <div class="card-title">
            <h2>Editar Bus</h2>
            <br>
            
            <form action="{{url('autobuses/'.$rowsb->id)}}" method="post" enctype="multipart/form-data">
             @csrf
              
              <input type="hidden" name="_method" value="PATCH">

              <div class="form-group">
                <label for="placa">Placa</label>
                <input required value="{{$rowsb->placa}}" type="text" class="form-control" id="placa" name="placa">
              </div>

              <br>

              <div class="form-group">
                <label for="capacidad">Capacidad</label>
                <input required value="{{$rowsb->capacidad}}" type="text" class="form-control" id="capacidad" name="capacidad">
              </div>

              <br>

              <div class="form-group">
                <label for="capacidad">Cilindraje</label>
                <input required value="{{$rowsb->cilindraje}}" type="text" class="form-control" id="capacidad" name="cilindraje">
              </div>

              <br>

              <div class="input-group mb-3">
                <label for="capacidad">foto</label>
                <br>
                  <input value="{{$rowsb->foto}}" type="file" class="form-control" placeholder="Foto" name="foto">
                  <input value="{{$rowsb->foto}}" type="text" class="form-control">
                  <div class="input-group-append">
                    <div class="input-group-text">
                      <span class="fas fa-user"></span>
                    </div>
                  </div>
              </div>

              <br>

              <div class="form-group">
                <label for="empresa">Licencia</label>
                <select required class="form-control" data-style="btn btn-link" id="empresa" name="licencia_id">
                  <option value="" selected disabled>Seleccione...</option>

                  @foreach ($rowsl as $row)
                  @if($row->id == $rowsb->licencia_id)
                  <option value="{{$row->id}}" selected>{{$row->tipo}}</option>
                  @else
                  <option value="{{$row->id}}">{{$row->tipo}}</option>
                  @endif
                  @endforeach

                </select>
              </div>

              <br>

              <div class="form-group">
                <label for="operacion">Estado Operativo</label>
                 <select required class="form-control" data-style="btn btn-link" id="operacion" name="operacion_estado">
                  @if($rowsb->operacion_estado == "Activo")
                  <option value="{{$rowsb->operacion_estado}}" selected>{{$rowsb->operacion_estado}}</option>
                  <option value="Inactivo">Inactivo</option>
                  @else
                  <option value="{{$rowsb->operacion_estado}}" selected>{{$rowsb->operacion_estado}}</option>
                  <option value="Activo">Activo</option>
                  @endif
                </select>
              </div>

               @if(Auth::user()->role_id==1)

               <div class="form-group">
                <label for="licencia">Estado de la licencia</label>
                 <select required class="form-control" data-style="btn btn-link" id="licencia" name="licencia_estado">
                  <option value="{{$rowsb->licencia_estado}}" selected disabled>{{$rowsb->licencia_estado}}</option>
                  <option value="Activa">Activa</option>
                  <option value="Inactiva">Inactiva</option>
                </select>
              </div>

              <br>

               <div class="form-group">
                <label for="empresa">Empresa</label>
                <select required class="form-control" data-style="btn btn-link" id="empresa" name="empresa_id">
                  <option value="" selected disabled>Seleccione...</option>

                  @foreach ($rows as $row)
                  @if($row->id == $rowsb->empresa_id)
                  <option value="{{$row->id}}" selected>{{$row->nombre}}</option>
                   @else
                  <option value="{{$row->id}}">{{$row->nombre}}</option>
                  @endif
                  @endforeach

                </select>
              </div>

              @endif
              
              <br>

              <button type="submit" class="btn btn-success">Submit</button>
              <a href="{{url('autobuses')}}" class="btn btn-info float-right">Volver</a>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/buses/index.blade.php
@extends('layouts.app', ['activePage' => 'typography', 'titlePage' => __('Typography')])

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Autobuses</h4>
        <p class="card-category"></p>
      </div>
      <div class="card-body">
        <div id="autobuses">
          <div class="card-title">
            <h2>Buses</h2>
            @if (Auth::user()->role_id==1 || Auth::user()->role_id==2)
            <a href="{{url('autobuses/create')}}" class="btn btn-info float-right">Crear</a>
            @endif
            <br>
            <br>
          </div>

         <div class="row col-md-12">
            @foreach ($rows as $row)
                
               
                    <div class="card mr-4" style="width: 20rem;">
                      <div class="card-body">
                        <h4 class="card-title" style="color: black!important"><strong>{{$row->placa}}</strong></h4>
                        <hr>
                        <img class="card-img-top mb-2" style="height: 180px" src="{{ url('public/images/'.$row->foto)  }}">
                        <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
                        <p class="card-text" style="margin-bottom: 0.7em!important">Capacidad: {{$row->capacidad}}</p>
                        <p class="card-text" style="margin-bottom: 0.7em!important">Cilindraje: {{$row->cilindraje}}</p>
                        <p class="card-text" style="margin-bottom: 0.7em!important">Licencia: {{$row->licencia->tipo}}</p>
                        <p class="card-text" style="margin-bottom: 0.7em!important">Estado de Licencia: {{$row->licencia_estado}}</p>
                        <p class="card-text" style="margin-bottom: 0.7em!important">Estado de Operación: {{$row->operacion_estado}}</p>
                         @if (Auth::user()->role_id==1)
                        <p class="card-text" style="margin-bottom: 0.7em!important">Empresa: {{$row->empresa->nombre}}</p>
                        @endif

                      @if (Auth::user()->role_id==1 || Auth::user()->role_id==2)
                      <div class="row">
                       <a href="{{url('licencias')}}" style="color: white" rel="tooltip" class="btn btn-info mr-2">
                                      <i class="material-icons">attach_money</i>
                       </a>
                      <a href="{{ route('autobuses.edit', $row->id) }}" rel="tooltip" class="btn btn-success mr-2" style="color: white">
                                    <i class="material-icons">edit</i>
                      </a>
                      <form  action="{{url('autobuses/'.$row->id)}}" method="post">
                                    @csrf
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button type="submit" rel="tooltip" class="btn btn-danger">
                                      <i class="material-icons">close</i>
                                    </button>
                      </form>
                      </div>
                      @endif
                      </div>
                    </div>
                
                
            @endforeach
    </div>   


          
        </div>
      </div>
    </div>
  </div>
</div>
@endsection